apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: flask-namespace
spec:
  type: NodePort
  selector:
    app: flask
  ports:
    - port: 5000        # internal cluster port
      targetPort: 5000  # pod ka port
      nodePort: 30007   # external port to access from host
